/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.90
 * Generated at: 2023-07-09 12:11:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Student Attendance System</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"http://netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"http://netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body\r\n");
      out.write("	style=\"background-image: url(images/31.jpg); background-size: 1480px;\">\r\n");
      out.write("	<nav class=\"navbar navbar-expand-sm bg-dark navbar-dark\">\r\n");
      out.write("		<!-- Brand/logo -->\r\n");
      out.write("		<img src=\"images/logo.png\" width=\"200px\" height=\"40px\" /> <a\r\n");
      out.write("			class=\"navbar-brand\" href=\"student_login.jsp\"><strong><span class=\"glyphicon glyphicon-user\"></span>&nbsp;Student Login</strong></a> <a\r\n");
      out.write("			class=\"navbar-brand\" href=\"index.jsp\"><strong><span class=\"glyphicon glyphicon-user\"></span>&nbsp;Admin Login</strong></a> <a\r\n");
      out.write("			class=\"navbar-brand\" href=\"\">&nbsp;</a> <a class=\"navbar-brand\"\r\n");
      out.write("			href=\"\">&nbsp;</a> <a class=\"navbar-brand\" href=\"\">&nbsp;</a> <a\r\n");
      out.write("			class=\"navbar-brand\" href=\"\">&nbsp;</a> <a class=\"navbar-brand\"\r\n");
      out.write("			href=\"\">&nbsp;</a> <a class=\"navbar-brand\" href=\"\">&nbsp;</a> <a\r\n");
      out.write("			class=\"navbar-brand\" href=\"\">&nbsp;</a> <a class=\"navbar-brand\"\r\n");
      out.write("			href=\"\">&nbsp;</a> <a class=\"navbar-brand\" href=\"\">&nbsp;</a> <a\r\n");
      out.write("			class=\"navbar-brand\" href=\"\">&nbsp;</a> <a class=\"navbar-brand\"\r\n");
      out.write("			href=\"\">&nbsp;</a><a class=\"navbar-brand\" href=\"\">&nbsp;</a><a\r\n");
      out.write("			class=\"navbar-brand\" href=\"\"><strong>");
      out.print((new java.util.Date()).toLocaleString());
      out.write("</strong></a>\r\n");
      out.write("\r\n");
      out.write("		<!-- Links -->\r\n");
      out.write("	</nav>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<img src=\"images/logo.png\" class=\"rounded float-right\"\r\n");
      out.write("			alt=\"Cinque Terre\" width=\"400\" height=\"106\">\r\n");
      out.write("\r\n");
      out.write("		<div id=\"loginbox\" style=\"margin-top: 50px;\"\r\n");
      out.write("			class=\"mainbox col-md-6  col-sm-6 col-sm-offset-7\">\r\n");
      out.write("			<div class=\"panel panel-default shadow p-3 mb-5\">\r\n");
      out.write("				<!-- <div class=\"panel-heading\">\r\n");
      out.write("					<div class=\"panel-title\" style=\"text-transform: uppercase;font-weight:bold;font-size:12px;\">Admin Sign In</div>\r\n");
      out.write("				</div> -->\r\n");
      out.write("				<div style=\"padding-top: 30px\" class=\"panel-body\">\r\n");
      out.write("					<h5>Please login to admin account</h5>\r\n");
      out.write("					<br>\r\n");
      out.write("					");

						String credential = (String) session.getAttribute("credential");
						if (credential != null) {
							session.removeAttribute("credential");
					
      out.write("\r\n");
      out.write("					<div class=\"alert alert-danger\" id=\"danger\">You have enter\r\n");
      out.write("						wrong credentials.</div>\r\n");
      out.write("					");

						}
					
      out.write("\r\n");
      out.write("					");

						String adminRegister = (String) session.getAttribute("message-success");
						if (adminRegister != null) {
							session.removeAttribute("message-success");
					
      out.write("\r\n");
      out.write("					<div class=\"alert alert-success\" id=\"success\">Account\r\n");
      out.write("						register successfully.</div>\r\n");
      out.write("					");

						}
					
      out.write("\r\n");
      out.write("					<div style=\"display: none\" id=\"login-alert\"\r\n");
      out.write("						class=\"alert alert-danger col-sm-12\"></div>\r\n");
      out.write("					<form id=\"loginform\" class=\"form-horizontal\" role=\"form\"\r\n");
      out.write("						action=\"AdminLogin\" method=\"post\">\r\n");
      out.write("						<label>User Name</label>\r\n");
      out.write("						<div style=\"margin-bottom: 15px\" class=\"input-group\">\r\n");
      out.write("							<span class=\"input-group-addon\"><i\r\n");
      out.write("								class=\"glyphicon glyphicon-user\">&nbsp;</i></span> <input\r\n");
      out.write("								id=\"login-username\" type=\"text\" class=\"form-control\"\r\n");
      out.write("								name=\"uname\" value=\"\" placeholder=\"User Name\"\r\n");
      out.write("								style=\"height: 30px;\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<label>Password</label>\r\n");
      out.write("						<div style=\"margin-bottom: 15px\" class=\"input-group\">\r\n");
      out.write("							<span class=\"input-group-addon\"><i\r\n");
      out.write("								class=\"glyphicon glyphicon-lock\"></i></span> <input id=\"login-password\"\r\n");
      out.write("								type=\"password\" class=\"form-control\" name=\"password\"\r\n");
      out.write("								placeholder=\"Password\" style=\"height: 30px;\" required=\"true\">\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div style=\"margin-top: 10px\" class=\"form-group\">\r\n");
      out.write("							<!-- Button -->\r\n");
      out.write("\r\n");
      out.write("							<div class=\"col-sm-8 controls\">\r\n");
      out.write("								<button type=\"submit\" value=\"\" class=\"btn btn-warning btn-lg\">\r\n");
      out.write("									<span class=\"glyphicon glyphicon-log-in\"></span> Login\r\n");
      out.write("								</button>\r\n");
      out.write("								<input type=\"reset\" value=\"Reset\" class=\"btn btn-danger btn-lg\">\r\n");
      out.write("								<a href=\"forgetPassword.jsp\" class=\"btn btn-link\"> Forget your password </a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<div class=\"col-md-12 control\">\r\n");
      out.write("								<div\r\n");
      out.write("									style=\"border-top: 1px solid #888; padding-top: 15px; font-size: 85%\">\r\n");
      out.write("									Don't have an account! <a href=\"#\"\r\n");
      out.write("										onClick=\"$('#loginbox').hide(); $('#signupbox').show()\">\r\n");
      out.write("										Sign Up Here </a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"signupbox\" style=\"display: none; margin-top: 50px\"\r\n");
      out.write("			class=\"mainbox col-md-6  col-sm-6 col-sm-offset-7\">\r\n");
      out.write("			<div class=\"panel panel-default\">\r\n");
      out.write("				<div class=\"panel-heading\">\r\n");
      out.write("					<div class=\"panel-title\">Sign Up</div>\r\n");
      out.write("					<div\r\n");
      out.write("						style=\"float: right; font-size: 100%; position: relative; top: -15px\">\r\n");
      out.write("						<a id=\"signinlink\" href=\"#\"\r\n");
      out.write("							onclick=\"$('#signupbox').hide(); $('#loginbox').show()\">Sign\r\n");
      out.write("							In</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"panel-body\">\r\n");
      out.write("					<form id=\"signupform\" class=\"form-horizontal\" role=\"form\"\r\n");
      out.write("						action=\"AdminRegistration\" method=\"post\" name=\"myForm\"\r\n");
      out.write("						onsubmit=\"return validateForm()\">\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label for=\"firstname\" class=\"col-md-3 control-label\">\r\n");
      out.write("								Name</label>\r\n");
      out.write("							<div class=\"col-md-9\">\r\n");
      out.write("								<input type=\"text\" class=\"form-control\" name=\"name\"\r\n");
      out.write("									placeholder=\"Name\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label for=\"email\" class=\"col-md-3 control-label\">Email</label>\r\n");
      out.write("							<div class=\"col-md-9\">\r\n");
      out.write("								<input type=\"text\" class=\"form-control\" name=\"email\"\r\n");
      out.write("									placeholder=\"Email Address\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label for=\"uname\" class=\"col-md-3 control-label\"> User\r\n");
      out.write("								Name</label>\r\n");
      out.write("							<div class=\"col-md-9\">\r\n");
      out.write("								<input type=\"text\" class=\"form-control\" name=\"uname\"\r\n");
      out.write("									placeholder=\"User Name\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label for=\"password\" class=\"col-md-3 control-label\">Password</label>\r\n");
      out.write("							<div class=\"col-md-9\">\r\n");
      out.write("								<input type=\"password\" class=\"form-control\" name=\"passwd\"\r\n");
      out.write("									placeholder=\"Password\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<!-- Button -->\r\n");
      out.write("							<div class=\"col-md-offset-3 col-md-9\">\r\n");
      out.write("								<input id=\"btn-signup\" type=\"submit\" class=\"btn btn-info\"\r\n");
      out.write("									value=\"Sign Up\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<div class=\"col-md-12 control\">\r\n");
      out.write("								<div\r\n");
      out.write("									style=\"border-top: 1px solid #888; padding-top: 15px; font-size: 85%\">\r\n");
      out.write("									Already Register.!! Please Login <a href=\"\"\r\n");
      out.write("										onClick=\"$('#loginbox').show(); $('#signupbox').hide()\">\r\n");
      out.write("										Login Here </a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	$(function() {\r\n");
      out.write("		$('#danger').delay(3000).show().fadeOut('slow');\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("	$(function() {\r\n");
      out.write("		$('#success').delay(3000).show().fadeOut('slow');\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	function validateForm() {\r\n");
      out.write("		var x = document.forms[\"myForm\"][\"name\"].value;\r\n");
      out.write("		if (x == \"\") {\r\n");
      out.write("			alert(\"Name must be filled out\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		var y = document.forms[\"myForm\"][\"email\"].value;\r\n");
      out.write("		if (y == \"\") {\r\n");
      out.write("			alert(\"Email id must be filled out\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		var z = document.forms[\"myForm\"][\"uname\"].value;\r\n");
      out.write("		if (z == \"\") {\r\n");
      out.write("			alert(\"User Name must be filled out\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		var p = document.forms[\"myForm\"][\"passwd\"].value;\r\n");
      out.write("		if (p == \"\") {\r\n");
      out.write("			alert(\"Password must be enter.\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
